#!/usr/bin/env python

"""Executable entry point to the IDE.

Important things depend upon the assumption that the value of
sys.path[0] is the directory which contains this file.  Violate that
assumption at your own risk."""

from __future__ import print_function

import os
import shutil

import wx

import settings
import sketchbook
from settings.preferences import preference
from SketchFrame import SketchFrame

#-----------------------------------------------------------------------------#

class MapleIDEApp(wx.App):
    def __init__(self, name):
        self.name = name
        wx.App.__init__(self, redirect=False)

    def OnInit(self):
        self.SetAssertMode(wx.PYAPP_ASSERT_EXCEPTION)

        sketch_f = sketchbook.most_recent_sketch_file()
        frame = SketchFrame(main_file=sketch_f)
        frame.Show(True)
        self.SetTopWindow(frame)

        return True

#-----------------------------------------------------------------------------#

def main():
    app = MapleIDEApp(u'Maple IDE')
    try:
        app.MainLoop()
    finally:
        if preference('build_dir_delete_on_exit'):
            build_dir = preference('build_dir')
            print(u'trashing build directory {0}'.format(build_dir))
            shutil.rmtree(build_dir)

if __name__ == '__main__':
    main()
